name: Continuos Integration with Github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: joselui3
          password: 840318Bd@
          
      - name: Setup Java JDK 
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Buid Eureka Naming Server Container Image 
        working-directory: .
        run: mvn spring-boot:build-image -DskipTests
