name: Continuous Integration with GitHub

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Java JDK 
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build Eureka Naming Server Container Image 
        working-directory: naming-server
        run: mvn spring-boot:build-image -DskipTests
